import type { CaptainItem } from "@/types/captain";
import { getTeam } from "./teams";

export const CAPTAINS: CaptainItem[] = [
  {
    id: "j25qrptugbc",
    image: {
      url: "/images/captain/j25qrptugbc.png",
      height: 850,
      width: 850,
    },
    name: "かんら",
    team: getTeam("e3li73yojqyq"),
    comment: "やるからには大いに楽しみながら優勝目指してがんがりまーす！",
    x_url: "https://x.com/kanra_kaiminch",
    youtube_url: "https://t.co/QiiFspavKT",
    voice_url: "https://youtube.com/shorts/cD71QQToqXw?feature=share",
  },
  {
    id: "z-nylbuhomt9",
    image: {
      url: "/images/captain/z-nylbuhomt9.png",
      height: 850,
      width: 850,
    },
    name: "星野夜空",
    team: getTeam("4l9vzx4a9gz"),
    comment: "メンバーの皆様をたくさん盛り上げてみんなで楽しく一つのチームにしていきたいです！\nよろしくお願いします！！",
    x_url: "https://x.com/yozora_pierrot",
    youtube_url: "https://t.co/SfSh7DoFw8",
  },
  {
    id: "32__382savcp",
    image: {
      url: "/images/captain/32__382savcp.png",
      height: 850,
      width: 850,
    },
    name: "山田恋羽",
    team: getTeam("92q7vscgxo"),
    comment: "どんな状況でも楽しんだ者勝ち❕\nピンクチームの可愛い所沢山皆に見てもらっちゃうもんね💞💞",
    x_url: "https://x.com/yamadakohane",
    youtube_url: "https://www.youtube.com/@yamadakohane1004",
    voice_url: "https://youtube.com/shorts/HF2_Nv8OA84?feature=share",
  },
  {
    id: "grqchzvv5zf",
    image: {
      url: "/images/captain/grqchzvv5zf.png",
      height: 850,
      width: 850,
    },
    name: "レオン=<br>オルカイーグル",
    team: getTeam("3ehcky1etdw"),
    comment: "＼ﾊﾟｯｶｰﾝ／\n翠迅チーム団長のレオン=オルカイーグルです！緑VTuberの底力、ここに証明しましょう！チーム全員一致団結！優勝するぞー！おー！",
    x_url: "https://x.com/reon_orcaeagle",
    youtube_url: "https://t.co/SW1Ls9AtoH",
    voice_url: "https://youtube.com/shorts/pkxdimvypDs?feature=share",
  },
  {
    id: "crk_iqvgr",
    image: {
      url: "/images/captain/crk_iqvgr.png",
      height: 706,
      width: 706,
    },
    name: "MyMe",
    team: getTeam("n5qmogp5h_z"),
    comment: "「声でかいで賞」と「一番元気で賞」では金賞受賞確定なので、この調子で黄昏チーム団長として優勝＆金メダル獲得していくぞーっ‼️👊 💥",
    x_url: "https://x.com/myme_gaua",
    youtube_url: "https://www.youtube.com/@myme_gaua",
    voice_url: "https://youtube.com/shorts/IMNqLAh3Igs",
  },
  {
    id: "z5ghlpzoequf",
    image: {
      url: "/images/captain/z5ghlpzoequf.png",
      height: 850,
      width: 850,
    },
    name: "紫虎ユラ",
    team: getTeam("sfypgr-1p35"),
    comment: "終わりたくなくなるぐらい楽しんでいきたいと思います!!",
    x_url: "https://x.com/shikou_yura",
    youtube_url: "https://www.youtube.com/channel/UCJuY8wAxkABbzPGkn-JsdHA",
  },
  {
    id: "24zvaidaq5",
    image: {
      url: "/images/captain/24zvaidaq5.png",
      height: 850,
      width: 850,
    },
    name: "奏俱らくり",
    team: getTeam("qz8mg90j4"),
    comment: "全部を白一色に染めてやるのは僕たち白雪チーム！！\nそして団長は僕！いっぱい走る気満々の怪物だっ\nさあ行こっ！僕たちのわくわくと優勝はすぐそこだ！！！",
    x_url: "https://x.com/karakurinagu_V",
    youtube_url: "https://www.youtube.com/@KAnaguRAKURI",
  },
  {
    id: "2ecbk7tl_n",
    image: {
      url: "/images/captain/2ecbk7tl_n.png",
      height: 850,
      width: 850,
    },
    name: "異吹ムレ",
    team: getTeam("ilrg1xnh0"),
    comment: "「黒夜組」団長の異世界人です。本大会の為、組の為、勝利の為、エンタメの為、楽しむ為に色々我慢できなくなるように組を導く所存でございます。行くわよアナタ達。よろしくお願いします。",
    x_url: "https://x.com/mure_kotobuki",
    youtube_url: "https://www.youtube.com/@murekotobuki",
    voice_url: "https://youtube.com/shorts/3Hw9UujITp8?feature=share",
  },
];
