import type { PlayerItem } from "@/types/player";
import { getTeam } from "./teams";
import { withIds } from "./withIds";

export const PLAYERS: PlayerItem[] = withIds<Omit<PlayerItem, "id">>([
  {
    icon: {
      url: "/images/player/cxons4pnl66.png",
      height: 600,
      width: 600,
    },
    name: "今際 サキ",
    kana: "いまわ さき",
    youtube_url: "https://www.youtube.com/@Saki_Imawa",
    x_url: "https://x.com/Saki_Imawa",
    team: getTeam("e3li73yojqyq"),
    updatedAt: "2026-08-28T01:20:03.471Z",
  },
  {
    icon: {
      url: "/images/player/rygag32hd7u.png",
      height: 600,
      width: 600,
    },
    name: "琥星 楓碧",
    kana: "こせい ふうあ",
    youtube_url: "https://www.youtube.com/@fuua715",
    voice_url: "https://youtube.com/shorts/Irio9zFyX-U",
    x_url: "https://x.com/Koseifua715",
    team: getTeam("3ehcky1etdw"),
    updatedAt: "2026-08-12T09:39:42.994Z",
  },
  {
    icon: {
      url: "/images/player/svnmfd0ltnc.png",
      height: 600,
      width: 600,
    },
    name: "発条 テクト",
    kana: "ぜんまい てくと",
    youtube_url: "http://www.youtube.com/@textecto",
    x_url: "https://x.com/tekuto0822",
    team: getTeam("3ehcky1etdw"),
    updatedAt: "2026-08-02T16:34:13.314Z",
  },
  {
    icon: {
      url: "/images/player/y-slnijqt1s.png",
      height: 600,
      width: 600,
    },
    name: "透間 七聖",
    kana: "すきま ななせ",
    youtube_url: "https://youtube.com/@schemerVII",
    voice_url: "https://youtube.com/shorts/nH3H8sN7Q1c?feature=share",
    x_url: "https://x.com/schemerVII",
    team: getTeam("3ehcky1etdw"),
    updatedAt: "2026-08-15T14:13:16.897Z",
  },
  {
    icon: {
      url: "/images/player/w5hk8xd6k.png",
      height: 600,
      width: 600,
    },
    name: "瀬戸内 神威",
    kana: "せとうち かむい",
    youtube_url: "https://www.youtube.com/@setouchikamui",
    x_url: "https://x.com/setonokamui",
    team: getTeam("3ehcky1etdw"),
    updatedAt: "2026-08-02T16:23:30.355Z",
  },
  {
    icon: {
      url: "/images/player/ag8mf-dmbj.png",
      height: 600,
      width: 600,
    },
    name: "室 風太郎",
    kana: "むろ ふうたろう",
    youtube_url: "https://www.youtube.com/channel/UCv5ZLHP17yDbH6OibIB6OUA",
    x_url: "https://x.com/taro_fu_taro",
    team: getTeam("3ehcky1etdw"),
    updatedAt: "2026-08-02T16:17:54.385Z",
  },
  {
    icon: {
      url: "/images/player/qo0jftvjmzku.png",
      height: 600,
      width: 600,
    },
    name: "はるのもり",
    youtube_url: "https://www.youtube.com/@はるのもり-n4u",
    x_url: "https://x.com/_halunomori",
    team: getTeam("3ehcky1etdw"),
    updatedAt: "2026-08-02T16:14:06.413Z",
  },
  {
    icon: {
      url: "/images/player/wygz9w3fr4x.png",
      height: 600,
      width: 600,
    },
    name: "スバひび(うたのおにいさん)",
    youtube_url: "https://www.youtube.com/@subahibi0109",
    x_url: "https://x.com/subahibi0427",
    team: getTeam("3ehcky1etdw"),
    updatedAt: "2026-08-02T16:06:46.463Z",
  },
  {
    icon: {
      url: "/images/player/e329wcgzb.png",
      height: 600,
      width: 600,
    },
    name: "ジョカ・ジョカ",
    youtube_url: "https://www.youtube.com/@cafe-o9topus",
    x_url: "https://x.com/jj_o9topus",
    team: getTeam("3ehcky1etdw"),
    updatedAt: "2026-08-02T16:03:58.762Z",
  },
  {
    icon: {
      url: "/images/player/vk3jz4yt9-pk.png",
      height: 600,
      width: 600,
    },
    name: "シエリス・アルクリス",
    youtube_url: "https://www.youtube.com/@SielisArklis63",
    voice_url: "https://youtube.com/shorts/Mz2MDY0fygw?feature=share",
    x_url: "https://x.com/SielisArklis63",
    team: getTeam("3ehcky1etdw"),
    updatedAt: "2026-08-26T18:45:05.768Z",
  },
  {
    icon: {
      url: "/images/player/0tgrzdiig4rx.png",
      height: 600,
      width: 600,
    },
    name: "夢兎 のん",
    kana: "ゆめと のん",
    youtube_url: "https://www.youtube.com/@yumeto__non",
    x_url: "https://x.com/yumeto__non",
    team: getTeam("92q7vscgxo"),
    updatedAt: "2026-08-02T15:43:57.766Z",
  },
  {
    icon: {
      url: "/images/player/zcsrqk67o.png",
      height: 600,
      width: 600,
    },
    name: "紡木 熊",
    kana: "つむぎ ゆう",
    youtube_url: "https://www.youtube.com/@yu_Tsumugi",
    x_url: "https://x.com/yuu_tsumugi",
    team: getTeam("92q7vscgxo"),
    updatedAt: "2026-08-02T15:43:15.863Z",
  },
  {
    icon: {
      url: "/images/player/9elurqp2pjev.png",
      height: 600,
      width: 600,
    },
    name: "桃宮 弥生",
    kana: "ももみや やよい",
    youtube_url: "https://www.youtube.com/@Yayoi_Momomiya",
    x_url: "https://x.com/Momomiya_Yayoi",
    team: getTeam("92q7vscgxo"),
    updatedAt: "2026-08-02T15:42:33.280Z",
  },
  {
    icon: {
      url: "/images/player/pwtu44x4_98j.png",
      height: 600,
      width: 600,
    },
    name: "赤 すずみ",
    kana: "あかき すずみ",
    youtube_url: "https://www.youtube.com/channel/UC817l0d1ZSWF3z-Jck5_9WA",
    x_url: "https://x.com/akakisuzumi",
    team: getTeam("92q7vscgxo"),
    updatedAt: "2026-08-02T15:41:42.659Z",
  },
  {
    icon: {
      url: "/images/player/n1rc--iec4.png",
      height: 600,
      width: 600,
    },
    name: "小守 にいと",
    kana: "こもり にいと",
    youtube_url: "https://www.youtube.com/channel/UCRcbZ6UiKREQ4V93dNuMcgg",
    voice_url: "https://youtube.com/shorts/cCiBA2Qpg9I?feature=share",
    x_url: "https://x.com/dareyanen210",
    team: getTeam("92q7vscgxo"),
    updatedAt: "2026-08-20T05:03:11.975Z",
  },
  {
    icon: {
      url: "/images/player/pua_v2lunvcq.png",
      height: 600,
      width: 600,
    },
    name: "御便 にゃぎ",
    kana: "おたより にゃぎ",
    youtube_url: "https://www.youtube.com/@OtayoriNyagi",
    x_url: "https://x.com/nyagigoya",
    team: getTeam("92q7vscgxo"),
    updatedAt: "2026-08-03T09:51:24.687Z",
  },
  {
    icon: {
      url: "/images/player/l52nd3mkm1kc.png",
      height: 600,
      width: 600,
    },
    name: "九条 ゆら",
    kana: "くじょう ゆら",
    youtube_url: "https://www.youtube.com/@kujyoYura",
    x_url: "https://x.com/yurayura_kujyo",
    team: getTeam("92q7vscgxo"),
    updatedAt: "2026-08-03T09:51:35.594Z",
  },
  {
    icon: {
      url: "/images/player/gz5dvr0pfn.png",
      height: 600,
      width: 600,
    },
    name: "しゃのらん",
    youtube_url: "https://www.youtube.com/@shanoran_0111",
    voice_url: "https://youtube.com/shorts/fcNVMw4tO7k?feature=share",
    x_url: "https://x.com/shanoran_0111",
    team: getTeam("92q7vscgxo"),
    updatedAt: "2026-08-15T14:16:11.422Z",
  },
  {
    icon: {
      url: "/images/player/s0lcp_ouii6.png",
      height: 600,
      width: 600,
    },
    name: "いおりょぎ",
    youtube_url: "https://www.youtube.com/@ioryogichang",
    x_url: "https://x.com/ioryogichang",
    team: getTeam("92q7vscgxo"),
    updatedAt: "2026-08-02T15:36:28.840Z",
  },
  {
    icon: {
      url: "/images/player/3dfoo73upk3.png",
      height: 600,
      width: 600,
    },
    name: "幽羽 戒人",
    kana: "ゆわ かいと",
    youtube_url: "https://www.youtube.com/@__YouWeRE_LEGNE",
    voice_url: "https://youtube.com/shorts/2tkKxWygYp8",
    x_url: "https://x.com/__YouWeRE_LEGNE",
    team: getTeam("ilrg1xnh0"),
    updatedAt: "2026-08-08T09:53:15.822Z",
  },
  {
    icon: {
      url: "/images/player/l5rni6gyvc.png",
      height: 600,
      width: 600,
    },
    name: "夜月 なぎ",
    kana: "よつき なぎ",
    youtube_url: "https://youtube.com/channel/UCjw1lvYHgXcKer0XYY3txNQ",
    voice_url: "https://youtube.com/shorts/3Irf1_4KXuk",
    x_url: "https://x.com/yotuki_nagi",
    team: getTeam("ilrg1xnh0"),
    updatedAt: "2026-08-12T09:34:09.150Z",
  },
  {
    icon: {
      url: "/images/player/y9vkwvw3uxp.png",
      height: 600,
      width: 600,
    },
    name: "波切 潮",
    kana: "なぎり うしお",
    youtube_url: "https://youtube.com/@nagiri_ushio",
    voice_url: "https://youtube.com/shorts/4qInRAoQ67c",
    x_url: "https://x.com/Nagiri_Ushio",
    team: getTeam("ilrg1xnh0"),
    updatedAt: "2026-08-09T18:45:19.055Z",
  },
  {
    icon: {
      url: "/images/player/407zc6whcy0.png",
      height: 600,
      width: 600,
    },
    name: "椎乃。",
    kana: "しいの",
    youtube_url: "https://www.youtube.com/@%E6%A4%8E%E4%B9%83-shiino",
    voice_url: "https://youtube.com/shorts/EdmFieV9Cdo?feature=share",
    x_url: "https://x.com/Shiino419_",
    team: getTeam("ilrg1xnh0"),
    updatedAt: "2026-08-09T18:43:48.609Z",
  },
  {
    icon: {
      url: "/images/player/38pfgqnu7u.png",
      height: 600,
      width: 600,
    },
    name: "海汐 しゃち",
    kana: "みしお しゃち",
    youtube_url: "https://www.youtube.com/@mishio_shachi_v",
    voice_url: "https://youtube.com/shorts/uOmkLpSZuoE",
    x_url: "https://x.com/mishio_shachi",
    team: getTeam("ilrg1xnh0"),
    updatedAt: "2026-08-09T18:46:39.137Z",
  },
  {
    icon: {
      url: "/images/player/459ygpqvj6sf.png",
      height: 600,
      width: 600,
    },
    name: "海栗 つばさ",
    kana: "みくり つばさ",
    youtube_url: "https://youtube.com/@mikuritsubasa",
    voice_url: "https://youtube.com/shorts/r-jjb6zLNaM",
    x_url: "https://x.com/mikuritsubasa",
    team: getTeam("ilrg1xnh0"),
    updatedAt: "2026-08-08T09:47:28.037Z",
  },
  {
    icon: {
      url: "/images/player/y3bqo369ms.png",
      height: 600,
      width: 600,
    },
    name: "安楽 うしろ",
    kana: "あんらく うしろ",
    youtube_url: "https://youtube.com/@anraku_usiro",
    x_url: "https://x.com/unrack_usiro",
    team: getTeam("ilrg1xnh0"),
    updatedAt: "2026-08-03T09:52:21.332Z",
  },
  {
    icon: {
      url: "/images/player/14upeho5xr.png",
      height: 600,
      width: 600,
    },
    name: "シエル",
    youtube_url: "https://www.youtube.com/@cielchannel0301",
    x_url: "https://x.com/Vtuber_CieL",
    team: getTeam("ilrg1xnh0"),
    updatedAt: "2026-08-02T15:20:13.075Z",
  },
  {
    icon: {
      url: "/images/player/7r1osmxoac1.png",
      height: 600,
      width: 600,
    },
    name: "サクシ",
    youtube_url: "https://www.youtube.com/@sakushi_stream",
    x_url: "https://x.com/sakushi_stream",
    team: getTeam("ilrg1xnh0"),
    updatedAt: "2026-08-02T15:18:25.185Z",
  },
  {
    icon: {
      url: "/images/player/4cds5aztcd.png",
      height: 600,
      width: 600,
    },
    name: "風海 ルツネ",
    kana: "ふうみ るつね",
    youtube_url: "https://www.youtube.com/@Fu-mi-Rutune",
    voice_url: "https://youtube.com/shorts/NANfv-acBxU?feature=share",
    x_url: "https://x.com/Fu_mi_Rutune",
    team: getTeam("4l9vzx4a9gz"),
    updatedAt: "2026-08-15T14:15:06.869Z",
  },
  {
    icon: {
      url: "/images/player/p8la1-t9yfs.png",
      height: 600,
      width: 600,
    },
    name: "青空 あのこ",
    kana: "あおぞら あのこ",
    youtube_url: "https://www.youtube.com/@aozora_anoco",
    x_url: "https://x.com/aonocco",
    team: getTeam("4l9vzx4a9gz"),
    updatedAt: "2026-08-03T09:52:36.104Z",
  },
  {
    icon: {
      url: "/images/player/2y47ur5bp.png",
      height: 600,
      width: 600,
    },
    name: "星綺 ゆな",
    kana: "ほしいろ ゆな",
    youtube_url: "https://youtube.com/@hoshiyuna",
    voice_url: "https://youtube.com/shorts/_M8M-MU1ioM?feature=share",
    x_url: "https://x.com/hoshiyuna_1",
    team: getTeam("4l9vzx4a9gz"),
    updatedAt: "2026-08-15T14:13:38.734Z",
  },
  {
    icon: {
      url: "/images/player/mm7kfztjxb1.png",
      height: 600,
      width: 600,
    },
    name: "時ノ音 ゲンキ",
    kana: "ときのね げんき",
    youtube_url: "https://www.youtube.com/channel/UCH4cWmeOeceG4HZDueWHKsw",
    x_url: "https://x.com/TokinoneGenki",
    team: getTeam("4l9vzx4a9gz"),
    updatedAt: "2026-08-03T09:57:37.706Z",
  },
  {
    icon: {
      url: "/images/player/cfq5-doc_iu.png",
      height: 600,
      width: 600,
    },
    name: "志夏",
    kana: "しなつ",
    youtube_url: "https://youtube.com/@shinatsu_274",
    x_url: "https://x.com/shinatsu_274",
    team: getTeam("4l9vzx4a9gz"),
    updatedAt: "2026-08-01T04:49:05.309Z",
  },
  {
    icon: {
      url: "/images/player/b51kj79qp.png",
      height: 600,
      width: 600,
    },
    name: "雅 はつる",
    kana: "みやび はつる",
    youtube_url: "https://www.youtube.com/@%E9%9B%85%E3%81%AF%E3%81%A4%E3%82%8B",
    voice_url: "https://youtube.com/shorts/go9Uf4VuM6M",
    x_url: "https://x.com/haturu_miyabi_v",
    team: getTeam("4l9vzx4a9gz"),
    updatedAt: "2026-08-12T09:35:51.867Z",
  },
  {
    icon: {
      url: "/images/player/g4y4883zk54p.png",
      height: 600,
      width: 600,
    },
    name: "雨破 レイン",
    kana: "うりわり れいん",
    youtube_url: "https://www.youtube.com/@Rainchannel0601",
    x_url: "https://x.com/Rain9ame",
    team: getTeam("4l9vzx4a9gz"),
    updatedAt: "2026-08-03T09:57:54.785Z",
  },
  {
    icon: {
      url: "/images/player/dwk-oj_q5.png",
      height: 600,
      width: 600,
    },
    name: "羽澄 ゆらん",
    kana: "はずみ ゆらん",
    youtube_url: "https://youtube.com/@hazumiyuran",
    x_url: "https://x.com/hazumi_yuran",
    team: getTeam("4l9vzx4a9gz"),
    updatedAt: "2026-08-03T09:58:03.358Z",
  },
  {
    icon: {
      url: "/images/player/qssisb3-aeec.png",
      height: 600,
      width: 600,
    },
    name: "カインヴェル",
    youtube_url: "https://www.youtube.com/@kainvelch.0713",
    voice_url: "https://youtube.com/shorts/4_PhUFAFJ0U?feature=share",
    x_url: "https://x.com/kain_masan",
    team: getTeam("4l9vzx4a9gz"),
    updatedAt: "2026-08-15T14:14:53.040Z",
  },
  {
    icon: {
      url: "/images/player/9a-_d6i1wrf.png",
      height: 600,
      width: 600,
    },
    name: "宙星 ルカ",
    kana: "ひろせ るか",
    youtube_url: "https://www.youtube.com/channel/UC-mfUJB6F501yxh6HAQ3wdA",
    x_url: "https://x.com/herose_ruka",
    team: getTeam("n5qmogp5h_z"),
    updatedAt: "2026-08-03T09:58:33.188Z",
  },
  {
    icon: {
      url: "/images/player/381tftsyjz.png",
      height: 600,
      width: 600,
    },
    name: "小花 ぺち",
    kana: "こはな ぺち",
    youtube_url: "https://www.youtube.com/@pechi_kohana",
    x_url: "https://x.com/pechi_kohana",
    team: getTeam("n5qmogp5h_z"),
    updatedAt: "2026-08-03T09:58:45.658Z",
  },
  {
    icon: {
      url: "/images/player/gr3bvtfw4dg.png",
      height: 600,
      width: 600,
    },
    name: "柑凪 しと",
    kana: "かんなぎ しと",
    youtube_url: "https://www.youtube.com/@sitositonomi",
    voice_url: "https://youtube.com/shorts/diZNZikEACA?feature=share",
    x_url: "https://x.com/sitositonomi",
    team: getTeam("n5qmogp5h_z"),
    updatedAt: "2026-08-19T17:09:05.358Z",
  },
  {
    icon: {
      url: "/images/player/i8c4936d1n0q.png",
      height: 600,
      width: 600,
    },
    name: "叶雨 つむぐ",
    kana: "かなめ つむぐ",
    youtube_url: "https://youtube.com/@kaname_tsumugu",
    x_url: "https://x.com/kanatsumu_v",
    team: getTeam("n5qmogp5h_z"),
    updatedAt: "2026-08-03T09:59:44.941Z",
  },
  {
    icon: {
      url: "/images/player/v717-gwdzn.png",
      height: 600,
      width: 600,
    },
    name: "卯月 春兎",
    kana: "うづき はると",
    youtube_url: "https://www.youtube.com/@HarutoU0410",
    x_url: "https://x.com/haruto_u0410",
    team: getTeam("n5qmogp5h_z"),
    updatedAt: "2026-08-03T09:59:51.294Z",
  },
  {
    icon: {
      url: "/images/player/znqkjy3sw77i.png",
      height: 600,
      width: 600,
    },
    name: "リトリッパー",
    youtube_url: "https://m.youtube.com/channel/UCEJ4rm6dX_R97WuiGFyS6Vg",
    voice_url: "https://youtube.com/shorts/6kNcFB4tmxU?feature=share",
    x_url: "https://x.com/retsan_12",
    team: getTeam("n5qmogp5h_z"),
    updatedAt: "2026-08-15T14:15:39.678Z",
  },
  {
    icon: {
      url: "/images/player/f169qa0de8av.png",
      height: 600,
      width: 600,
    },
    name: "まるみん",
    youtube_url: "https://youtube.com/channel/UCu6i_zUkxQkoz4dAmHBf57Q",
    x_url: "https://x.com/maruminchannel",
    team: getTeam("n5qmogp5h_z"),
    updatedAt: "2026-07-26T13:36:46.473Z",
  },
  {
    icon: {
      url: "/images/player/i0glx9p-upc.png",
      height: 600,
      width: 600,
    },
    name: "チャーはん",
    youtube_url: "https://youtube.com/@chahan-is-good",
    x_url: "https://x.com/tyaahann0505050",
    team: getTeam("n5qmogp5h_z"),
    updatedAt: "2026-08-31",
  },
  {
    icon: {
      url: "/images/player/7kadwq3m4.png",
      height: 600,
      width: 600,
    },
    name: "イザナミアヌ",
    youtube_url: "https://youtube.com/channel/UCH7QRxCsd_Dt-CI6ZH78TVQ",
    x_url: "https://x.com/izanami_anu0x0",
    team: getTeam("n5qmogp5h_z"),
    updatedAt: "2026-07-26T13:30:26.695Z",
  },
  {
    icon: {
      url: "/images/player/bqmb51olq.png",
      height: 600,
      width: 600,
    },
    name: "眞神 白狼",
    kana: "まがみ しろ",
    youtube_url: "https://youtube.com/channel/UCXvzOMJUfWs-hh9UCk4yv1Q",
    x_url: "https://x.com/Shiro_Magami",
    team: getTeam("qz8mg90j4"),
    updatedAt: "2026-08-03T09:59:59.717Z",
  },
  {
    icon: {
      url: "/images/player/g54qdf2syw7.png",
      height: 600,
      width: 600,
    },
    name: "夜見月 アルト",
    kana: "よみづき あると",
    youtube_url: "https://www.youtube.com/@yomizuki_aluto",
    x_url: "https://x.com/Aluto_yomizuki",
    team: getTeam("qz8mg90j4"),
    updatedAt: "2026-08-03T10:00:19.334Z",
  },
  {
    icon: {
      url: "/images/player/04kr6npc7a20.png",
      height: 600,
      width: 600,
    },
    name: "餅乃 ふぉか",
    kana: "もちの ふぉか",
    youtube_url: "https://www.youtube.com/@mochino_foca",
    x_url: "https://x.com/mochino_foca84",
    team: getTeam("qz8mg90j4"),
    updatedAt: "2026-08-03T10:00:31.014Z",
  },
  {
    icon: {
      url: "/images/player/ig1bfjx11ux8.png",
      height: 600,
      width: 600,
    },
    name: "白望 イヅネ",
    kana: "はくぼう いづね",
    youtube_url: "https://www.youtube.com/@Hakubou_Izune",
    x_url: "https://x.com/Hakubou_Izune",
    team: getTeam("qz8mg90j4"),
    updatedAt: "2026-07-26T13:23:08.338Z",
  },
  {
    icon: {
      url: "/images/player/d5lz7u_sry.png",
      height: 600,
      width: 600,
    },
    name: "蒼白獅 れお",
    kana: "そうびゃくし れお",
    youtube_url: "https://www.youtube.com/@soubyakushi-leo",
    x_url: "https://x.com/leo_soubyakushi",
    team: getTeam("qz8mg90j4"),
    updatedAt: "2026-08-03T10:00:50.227Z",
  },
  {
    icon: {
      url: "/images/player/akiu3uvfe.png",
      height: 600,
      width: 600,
    },
    name: "星月 りおな",
    kana: "ほしづき りおな",
    youtube_url: "https://youtube.com/@hoshizuki_riona",
    x_url: "https://x.com/hoshizuki_riona",
    team: getTeam("qz8mg90j4"),
    updatedAt: "2026-08-03T10:01:43.633Z",
  },
  {
    icon: {
      url: "/images/player/gy1p-7wogb.png",
      height: 600,
      width: 600,
    },
    name: "小羽音 いこい",
    kana: "ささはね いこい",
    youtube_url: "https://www.youtube.com/@sasahane_ikoi",
    x_url: "https://x.com/sasahane151",
    team: getTeam("qz8mg90j4"),
    updatedAt: "2026-08-03T10:04:40.535Z",
  },
  {
    icon: {
      url: "/images/player/mt4hhse-au2.png",
      height: 600,
      width: 600,
    },
    name: "三鍵 とびら",
    kana: "みかぎ とびら",
    youtube_url: "https://www.youtube.com/channel/UCnCLd_pH8prU16lCup-Biqg",
    x_url: "https://x.com/MikagiVtuber",
    team: getTeam("qz8mg90j4"),
    updatedAt: "2026-08-03T10:04:48.036Z",
  },
  {
    icon: {
      url: "/images/player/eno5d6lpczyk.png",
      height: 600,
      width: 600,
    },
    name: "花里 透",
    kana: "はなさと とおる",
    youtube_url: "https://youtube.com/channel/UClmUkjzZ6f4XvTNiMcdEm6A",
    x_url: "https://x.com/hanasato_tooru",
    team: getTeam("qz8mg90j4"),
    updatedAt: "2026-08-03T10:04:54.418Z",
  },
  {
    icon: {
      url: "/images/player/x8pc2qqjvyu.png",
      height: 600,
      width: 600,
    },
    name: "波宮-Hamia-",
    kana: "はみあ",
    youtube_url: "https://youtube.com/@slp_hamia",
    voice_url: "https://youtube.com/shorts/jhNOP3Az-gM",
    x_url: "https://x.com/slp_hamia",
    team: getTeam("sfypgr-1p35"),
    updatedAt: "2026-08-08T09:55:38.116Z",
  },
  {
    icon: {
      url: "/images/player/m3p1ho3j84v6.png",
      height: 600,
      width: 600,
    },
    name: "宙乃 音斗",
    kana: "そらの おと",
    youtube_url: "https://www.youtube.com/@0tosorano.34",
    voice_url: "https://youtube.com/shorts/1X7-FJj8vig?feature=share",
    x_url: "https://x.com/0to_Sorano",
    team: getTeam("sfypgr-1p35"),
    updatedAt: "2026-08-15T14:14:17.735Z",
  },
  {
    icon: {
      url: "/images/player/r3f3c4z-wb.png",
      height: 600,
      width: 600,
    },
    name: "瀬々名 ルビー",
    kana: "せせな るびー",
    youtube_url: "https://www.youtube.com/@Sesenaruby",
    x_url: "https://x.com/HaaMvq",
    team: getTeam("sfypgr-1p35"),
    updatedAt: "2026-08-03T10:05:04.080Z",
  },
  {
    icon: {
      url: "/images/player/9qc-ad2n5.png",
      height: 600,
      width: 600,
    },
    name: "検察側の証人",
    kana: "けんさつがわのしょうにん",
    youtube_url: "https://www.youtube.com/@kensatsu_syonin",
    x_url: "https://x.com/kensatsu_syonin",
    team: getTeam("sfypgr-1p35"),
    updatedAt: "2026-07-26T12:55:44.217Z",
  },
  {
    icon: {
      url: "/images/player/inwaatrgbrj.png",
      height: 600,
      width: 600,
    },
    name: "月影 ルイ",
    kana: "つきかげ るい",
    youtube_url: "https://youtube.com/@rui_tsukikage",
    voice_url: "https://youtube.com/shorts/WSnawllPUVw?feature=share",
    x_url: "https://x.com/rui__tsukikage",
    team: getTeam("sfypgr-1p35"),
    updatedAt: "2026-08-19T17:09:28.786Z",
  },
  {
    icon: {
      url: "/images/player/egwqko_47ik.png",
      height: 600,
      width: 600,
    },
    name: "音頭・ルゥ",
    kana: "おんど るぅ",
    youtube_url: "https://www.youtube.com/@ondo_ruu_Vtuber",
    x_url: "https://x.com/ondo_ru",
    team: getTeam("sfypgr-1p35"),
    updatedAt: "2026-07-24T03:17:04.564Z",
  },
  {
    icon: {
      url: "/images/player/8etp0d5snn1t.png",
      height: 600,
      width: 600,
    },
    name: "絵餓鬼 ザビ丸",
    kana: "えがき ざびまる",
    youtube_url: "https://youtube.com/channel/UCk2GVt5-E6mPM-zYIzs_l1Q?si=W8G3BY06fOWURU2m",
    x_url: "https://x.com/ZABIMALL_VT",
    team: getTeam("sfypgr-1p35"),
    updatedAt: "2026-08-03T10:05:24.134Z",
  },
  {
    icon: {
      url: "/images/player/s6o75uul8-n.png",
      height: 600,
      width: 600,
    },
    name: "しにー",
    youtube_url: "https://www.youtube.com/@sinichyan0423",
    voice_url: "https://youtube.com/shorts/11XPpibxUQ8?feature=share",
    x_url: "https://x.com/sinichan0423",
    team: getTeam("sfypgr-1p35"),
    updatedAt: "2026-08-15T14:15:24.094Z",
  },
  {
    icon: {
      url: "/images/player/k7x0v2c3f.png",
      height: 600,
      width: 600,
    },
    name: "緋繧 めいや",
    kana: "ひうん めいや",
    youtube_url: "https://www.youtube.com/channel/UCE1x9QhSGuUJ91MaPx7al8w",
    voice_url: "https://youtube.com/shorts/aJPRU765Qhg",
    x_url: "https://x.com/hiunmeiya_zonbi",
    team: getTeam("e3li73yojqyq"),
    updatedAt: "2026-08-09T18:47:37.548Z",
  },
  {
    icon: {
      url: "/images/player/s6vwzcmikb.png",
      height: 600,
      width: 600,
    },
    name: "柊 狐月",
    kana: "ひいらぎ こげつ",
    youtube_url: "https://www.youtube.com/@kogetsu_hiiragi",
    x_url: "https://x.com/kogetsu_hiiragi",
    team: getTeam("e3li73yojqyq"),
    updatedAt: "2026-08-03T10:01:08.624Z",
  },
  {
    icon: {
      url: "/images/player/rzeym6q4bz.png",
      height: 600,
      width: 600,
    },
    name: "破紅 蒼磨",
    kana: "はぐれ そうま",
    youtube_url: "https://www.youtube.com/@HagureSouma",
    voice_url: "https://youtube.com/shorts/c3MqJL-JR-g",
    x_url: "https://x.com/hagure_souma",
    team: getTeam("e3li73yojqyq"),
    updatedAt: "2026-08-08T09:51:36.598Z",
  },
  {
    icon: {
      url: "/images/player/1413e9clrk7.png",
      height: 600,
      width: 600,
    },
    name: "りく猫",
    kana: "りくねこ",
    youtube_url: "https://youtube.com/@rikuneko298",
    x_url: "https://x.com/rikuneko298",
    team: getTeam("e3li73yojqyq"),
    updatedAt: "2026-07-24T03:24:52.245Z",
  },
  {
    icon: {
      url: "/images/player/1sw3p45_xl.png",
      height: 600,
      width: 600,
    },
    name: "雪風 スト",
    kana: "ゆきかぜ すと",
    youtube_url: "https://youtube.com/channel/UCA9-hPd9Dfq9Pta8GmaTDqA",
    voice_url: "https://youtube.com/shorts/omP00aOkbj4",
    x_url: "https://x.com/01stripe",
    team: getTeam("e3li73yojqyq"),
    updatedAt: "2026-08-26T18:43:42.596Z",
  },
  {
    icon: {
      url: "/images/player/musf2m767.png",
      height: 600,
      width: 600,
    },
    name: "犬牙 ユウ",
    kana: "けんが ゆう",
    youtube_url: "https://www.youtube.com/@kenga-yuu",
    x_url: "https://x.com/kengayuu",
    team: getTeam("e3li73yojqyq"),
    updatedAt: "2026-07-24T03:25:52.301Z",
  },
  {
    icon: {
      url: "/images/player/76gqr48i5_ov.png",
      height: 600,
      width: 600,
    },
    name: "ことあ",
    youtube_url: "https://www.youtube.com/@Okitsune_Kotoa",
    x_url: "https://twitter.com/Kotoa_okitsune",
    team: getTeam("sfypgr-1p35"),
    updatedAt: "2026-07-21T17:05:33.487Z",
  },
  {
    icon: {
      url: "/images/player/83zoxdam322.png",
      height: 600,
      width: 600,
    },
    name: "ロゼッタ･(以下略)･クストーデ",
    youtube_url: "https://youtube.com/@rosetta_kawaiivt",
    voice_url: "https://youtube.com/shorts/quQtcgcj3DE",
    x_url: "https://x.com/rosetta_kawaiiv",
    team: getTeam("e3li73yojqyq"),
    updatedAt: "2026-08-08T09:45:38.318Z",
  },
  {
    icon: {
      url: "/images/player/0y4tozx85cjo.png",
      height: 600,
      width: 600,
    },
    name: "白金 燐",
    kana: "しろがね りん",
    youtube_url: "https://www.youtube.com/@ojo1206",
    x_url: "https://x.com/akairo_ojo",
    team: getTeam("e3li73yojqyq"),
    updatedAt: "2026-07-24T03:22:21.323Z",
  },
  {
    icon: {
      url: "/images/player/q3du2s3hsuaz.png",
      height: 600,
      width: 600,
    },
    name: "ガルゼル",
    youtube_url: "https://youtube.com/channel/UCQ6B-a2reuCb_ZdHUwaGedw",
    voice_url: "https://youtube.com/shorts/7be1OPR1uY8",
    x_url: "https://x.com/garuzeru",
    team: getTeam("e3li73yojqyq"),
    updatedAt: "2026-08-08T09:41:52.939Z",
  },
]);
